### ISSUE TITLE
Update the way EPSS data is reported

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/cve2stix#25]
Currently we define EPSS scoring in the vulnerability object

this has led to a downstream issue with ACTIP

https://dogesec.slack.com/archives/D05L8JEAM1N/p1728310311981869

As such, we need to remove EPSS scoring from Vulnerability objects, and instead use a dedicated object 

Firstly, we need to import the new extension-defintion object to every bundle

https://raw.githubusercontent.com/muchdogesec/stix2extensions/refs/heads/main/extension-definitions/properties/note-epss-scoring.json

Secondly, we need to model the actual note object as follows

```json
{
    "type": "note",
    "spec_version": "2.1",
    "id": "note--<UUID v5 using namespace + content>",
    "created_by_ref": "identity--562918ee-d5da-5579-b6a1-fae50cc6bad3",
    "created": "<EARLIEST EPSS RECORDED>",
    "modified": "<LATEST EPSS RECORDED>",
    "content": "EPSS Score for <CVE ID>",
    "object_refs": [
        "vulnerability--CVE-vuln-object"
    ],
    "object_marking_refs": [
        "marking-definition--94868c89-83c2-464b-929b-a1a8aa3c8487",
        "marking-definition--562918ee-d5da-5579-b6a1-fae50cc6bad3"
    ],
    "extensions": {
        "extension-definition--efd26d23-d37d-5cf2-ac95-a101e46ce11d": {
            "extension_type": "toplevel-property-extension"
        }
    },
    "x_epss": [
        {
            "date": "<EPSS DATE>",
            "percentile": "<EPSS PERCENTILE>",
            "score": "<EPSS SCORE>"
        },
    ]
}
```

e.g.

https://github.com/muchdogesec/stix2extensions/blob/main/example_objects/properties/note--8d62e369-463f-59d7-825b-09185aed39dc.json

**Comment by himynamesdave** [comment]
@fqrious its working well.

I request one small change. Can you change the UUID part of the `id` of notes to match the UUID part of the corresponding vulnerability object?

**Comment by fqrious** [comment]
okay
